### ISSUE TITLE
Cannot see the cvolumetric clouds...

### ISSUE THREAD

**Issue by dspcad** [Depersonalizc/volumetric-clouds#9]
I tried to use your tool to generate volumetric clouds but it seems not working....
![image](https://github.com/Depersonalizc/volumetric-clouds/assets/22190436/8c712ee8-75d2-4782-9eca-147939905e3e)

**Comment by Endlessio** [comment]
try to uncomment realtime.cpp line 416-418

**Comment by Depersonalizc** [comment]
Fixed!
